import json, os, re, sys
from pathlib import Path

import numpy as np
from playwright.sync_api import sync_playwright
from PIL import Image, ImageChops

BASE = "http://localhost:3100"
OUT = Path("/home/jiromanalo/Projects/UNI-verse/.qa/out")
PROJ = Path("/home/jiromanalo/Projects/UNI-verse")
OUT.mkdir(parents=True, exist_ok=True)

EMAIL = "arthur-qa@qa.local"
PASSWORD = "Passw0rd!qa"
USERNAME = "arthur_qa"

results = []
def check(name, ok, info=""):
    results.append((name, bool(ok), info))
    mark = "PASS" if ok else "FAIL"
    print(f"[QA] {mark} - {name}" + (f" ({info})" if info else ""))

def load_env():
    env = {}
    for fn in (".env", ".env.local"):
        pf = PROJ / fn
        if not pf.exists():
            continue
        for line in pf.read_text().splitlines():
            line = line.split("#", 1)[0].strip()
            if "=" in line:
                k, v = line.split("=", 1)
                k = k.strip()
                v = v.strip()
                if (v[:1] == v[-1:] and v[:1] in ("'", '"')) and len(v) >= 2:
                    v = v[1:-1]
                env[k] = v
    return env

def bootstrap_qa_user(env, theme_id="arthur"):
    import subprocess
    supabase_url = env.get("SUPABASE_URL") or env.get("NEXT_PUBLIC_SUPABASE_URL") or ""
    service_key = env.get("SUPABASE_SERVICE_ROLE_KEY") or ""
    db_url = env.get("DATABASE_URL") or env.get("DIRECT_URL") or ""
    if not supabase_url or not service_key or not db_url:
        return None

    code = f"""
const {{ Client }} = require('pg');
const {{ createClient }} = require('@supabase/supabase-js');
(async () => {{
  const sb = createClient({json.dumps(supabase_url)}, {json.dumps(service_key)}, {{
    auth: {{ autoRefreshToken: false, persistSession: false }}
  }});

  // 1. Ensure supabase auth user exists (email confirmed)
  const email = {json.dumps(EMAIL)};
  const password = {json.dumps(PASSWORD)};
  const username = {json.dumps(USERNAME)};
  let uid;
  const listRes = await sb.auth.admin.listUsers({{ filter: 'email=eq.' + email }});
  const existing = (listRes.data?.users || []).find(u => u.email === email);
  if (existing) {{
    uid = existing.id;
    // ensure email is confirmed
    await sb.auth.admin.updateUserById(uid, {{ email_confirm: true }});
  }} else {{
    const createRes = await sb.auth.admin.createUser({{
      email, password, email_confirm: true,
      user_metadata: {{ username }}
    }});
    uid = createRes.data.user.id;
  }}

  // 2. Upsert app User row + purchase + theme
  const c = new Client({{ connectionString: {json.dumps(db_url)} }});
  await c.connect();
  await c.query('INSERT INTO "User" ("id","email","username","coins","createdAt","updatedAt") VALUES ($1,$2,$3,1000,now(),now()) ON CONFLICT ("id") DO UPDATE SET coins=1000',
    [uid, email, username]);
  await c.query('INSERT INTO "PurchasedTheme" ("id","userId","themeId","purchasedAt") VALUES ($1,$2,$3,now()) ON CONFLICT DO NOTHING',
    ['qa-' + uid, uid, {json.dumps(theme_id)}]);
  await c.query('INSERT INTO "UserSettings" ("id","userId","profileThemeId") VALUES ($1,$2,$3) ON CONFLICT ("userId") DO UPDATE SET "profileThemeId" = EXCLUDED."profileThemeId"',
    ['qa-' + uid, uid, {json.dumps(theme_id)}]);
  await c.end();

  // 3. Sign in to get session tokens
  const {{ data, error }} = await sb.auth.signInWithPassword({{ email, password }});
  if (error || !data?.session) {{
    console.error('SIGNIN_FAIL', error?.message || 'no session');
    process.exit(1);
  }}
  console.log(JSON.stringify({{
    access: data.session.access_token,
    refresh: data.session.refresh_token,
    uid: uid
  }}));
}})().catch(e => {{ console.error('BOOT_FAIL', e.message || e); process.exit(1); }});
"""
    r = subprocess.run(["node", "-e", code], capture_output=True, text=True, cwd=PROJ, timeout=30)
    if r.returncode != 0:
        print("  bootstrap stderr:", r.stderr[-500:])
        return None
    try:
        return json.loads(r.stdout.strip())
    except Exception:
        print("  bootstrap stdout:", r.stdout.strip()[:200])
        return None

env = load_env()

with sync_playwright() as p:
    browser = p.chromium.launch(headless=True)

    # 1. served asset sanity (no auth needed)
    api = p.request.new_context()
    r = api.get(BASE + "/themes/arthur.gif")
    body = r.body()
    local = (PROJ / "public/themes/arthur.gif").read_bytes()
    check("gif served 200", r.status == 200, str(r.status))
    check("gif served == regenerated bytes", body == local, f"{len(body)}B served {len(local)}B local")

    # 2. bootstrap user + inject session cookies
    tokens = bootstrap_qa_user(env)
    check("bootstrap qa user", tokens is not None, "got tokens" if tokens else "failed")
    if not tokens:
        print("\n=== CANNOT PROCEED WITHOUT SESSION ===")
        browser.close()
        sys.exit(1)

    # 3. light-mode page via real UI login (app sets the correct session cookies)
    page = browser.new_page()
    errs = []
    page.on("console", lambda m: errs.append(m.text) if m.type == "error" else None)
    page.goto(BASE + "/login", wait_until="networkidle")
    page.fill("#email", EMAIL)
    page.fill("#password", PASSWORD)
    page.click('form button[type="submit"]')
    page.wait_for_timeout(3000)

    who = page.evaluate("""() => fetch('/api/me').then(r => (r.ok ? r.json() : Promise.resolve(null)))
                                       .then(d => d ? (d.data || d).username : null).catch(() => null)""")
    check("logged in as " + USERNAME, who == USERNAME, str(who))

    page.goto(BASE + "/profile/" + USERNAME, wait_until="networkidle")

    def dismiss_modal(pg):
        try:
            skip = pg.locator('button', has_text="Skip for Now")
            if skip.count() > 0 and skip.first.is_visible():
                skip.first.click()
                pg.wait_for_timeout(600)
        except Exception:
            pass

    dismiss_modal(page)
    page.wait_for_timeout(1800)

    present = page.evaluate("""() => {
      const root = document.querySelector('[data-theme="arthur"]');
      const s = document.querySelector('.theme-sticker');
      const gif = document.querySelector('.theme-sticker-gif');
      return { root: !!root, sticker: !!s, gifVisible: !!gif && getComputedStyle(gif).display !== 'none' };
    }""")
    check("arthur theme data attr", bool(present.get("root")))
    check("sticker present", bool(present.get("sticker")))

    def always_transparent_gif_px():
        gif = Image.open(PROJ / "public/themes/arthur.gif")
        acc = None
        for f in range(gif.n_frames):
            gif.seek(f)
            a = gif.convert("RGBA").getchannel("A")
            p = a.point(lambda v: 255 if v == 0 else 0)
            acc = p if acc is None else ImageChops.multiply(acc, p)
        data = acc.load()
        pts = []
        for gy in range(0, acc.height, 12):
            for gx in range(0, acc.width, 12):
                if data[gx, gy]:
                    pts.append((gx, gy))
        return pts

    def gce_frame_flags(data):
        """[(frame_no, transp_flag, transp_idx, disposal)] parsed from raw GIF bytes."""
        gct_n = 1 << ((data[10] & 7) + 1)
        i = 13 + 3 * gct_n
        out, fnum = [], -1
        while i < len(data) - 1:
            b = data[i]
            if b == 0x2C:
                fnum += 1
                lc = data[i + 9]
                lsz = 3 * (1 << ((lc & 7) + 1)) if (lc & 0x80) else 0
                i += 10 + lsz + 1
                while data[i] != 0:
                    i += 1 + data[i]
                i += 1
            elif b == 0x21 and i + 1 < len(data) and data[i + 1] == 0xF9:
                packed = data[i + 3]
                out.append((fnum, bool(packed & 1), data[i + 6], (packed >> 2) & 7))
                i += 8
            elif b == 0x21:
                i += 2
                while i < len(data) and data[i] != 0:
                    i += 1 + data[i]
                i += 1
            elif b == 0x3B:
                break
            else:
                i += 1
        return out

    def check_sky_via_gif_alpha(name):
        page.screenshot(path=str(OUT / "arthur_hero_light.png"))
        im = Image.open(OUT / "arthur_hero_light.png").convert("RGB")
        im_np = np.asarray(im).astype(int)
        rect = page.evaluate("""() => {
          const s = document.querySelector('.theme-sticker-gif') ||
                    document.querySelector('.theme-sticker-poster');
          const h = document.querySelector('.theme-hero');
          if (!s || !h) return null;
          const r = s.getBoundingClientRect(), hb = h.getBoundingClientRect();
          return { x: r.x, y: r.y, w: r.width, h: r.height, hx: hb.x, hy: hb.y, hw: hb.width, hh: hb.height };
        }""")
        if not rect:
            check(name + " elements", False)
            return
        H, W = im_np.shape[:2]
        matte = np.array([189, 121, 70])
        dark = np.array([64, 64, 64])
        bad, mat, n = 0, 0, 0
        for (gx, gy) in always_transparent_gif_px():
            xp = rect["x"] + gx * rect["w"] / 360.0
            yp = rect["y"] + gy * rect["h"] / 360.0
            xi, yi = int(xp), int(yp)
            if not (rect["hx"] + 8 <= xi < rect["hx"] + rect["hw"] - 8
                    and rect["hy"] + 8 <= yi < rect["hy"] + rect["hh"] * 0.6):
                continue
            if not (0 <= xi < W and 0 <= yi < H):
                continue
            got = im_np[yi, xi]
            n += 1
            if np.abs(got - matte).sum() <= 36:
                mat += 1
            if int(got.mean()) < 64:
                bad += 1
        if n == 0:
            check(name + " sky samples", False)
            return
        # Small counts of dark pixels are animation-edge/rounded-border bleed at the
        # sticker's rim; a genuine slab would hit a large fraction of samples.
        allowed = max(4, int(round(n * 0.06)))
        check(name, bad <= allowed and mat == 0,
              f"sky px={n} dark/white={bad} matte={mat}/{n} (allowed<={allowed})")

    check_sky_via_gif_alpha("light-mode sticker area = sky (no opaque slab / dark or white boxes)")
    check("every-frame GCE transparency in served gif", all(
        (tf and ti == 254) for (_, tf, ti, _) in gce_frame_flags(body)),
        f"{len(gce_frame_flags(body))} frames parsed")
    txt = page.evaluate("""() => { const b = document.querySelector('.theme-sticker');
                             return b ? JSON.stringify(b.getBoundingClientRect()) : null; }""")
    print("  sticker box:", txt)

    # 4. dark mode
    page2 = browser.new_page(color_scheme="dark")
    page2.context.add_cookies(page.context.cookies())
    page2.goto(BASE + "/profile/" + USERNAME, wait_until="networkidle")
    page2.wait_for_timeout(1800)
    dismiss_modal(page2)
    box2 = page2.evaluate("""() => { const el = document.querySelector('.theme-sticker');
      if (!el) return null; const r = el.getBoundingClientRect();
      return { x: Math.round(r.x), y: Math.round(r.y + r.height*0.12), w: Math.round(r.width), h: Math.round(r.height*0.76) }; }""")
    page2.screenshot(path=str(OUT / "arthur_hero_dark.png"))
    im2 = Image.open(OUT / "arthur_hero_dark.png").convert("RGB")
    px2 = im2.load()
    sam2 = []
    if box2:
        for dx in range(4, box2["w"] - 4, 10):
            for dy in (4, (box2["h"] // 3)):
                if 0 <= box2["x"] + dx < im2.size[0] and 0 <= box2["y"] + dy < im2.size[1]:
                    sam2.append(px2[box2["x"] + dx, box2["y"] + dy])
    if sam2:
        n2 = len(sam2)
        avg2 = tuple(sum(s[i] for s in sam2) // n2 for i in range(3))
        dark2 = sum(1 for s in sam2 if sum(s) < 320)
        check("dark-mode sticker area readable (avg brightness > 60)",
              sum(avg2) // 3 > 60 and dark2 / n2 < 0.5, f"avg={avg2} dark={dark2}/{n2}")
    else:
        check("dark-mode sticker area box", False)

    # 5. reduced-motion poster path
    page3 = browser.new_page(reduced_motion="reduce")
    page3.context.add_cookies(page.context.cookies())
    page3.goto(BASE + "/profile/" + USERNAME, wait_until="networkidle")
    page3.wait_for_timeout(1500)
    dismiss_modal(page3)
    poster_visible = page3.evaluate("""() => {
      const g = document.querySelector('.theme-sticker-gif');
      const pt = document.querySelector('.theme-sticker .theme-sticker-poster');
      return { gifHidden: !!g && getComputedStyle(g).display === 'none',
               posterShown: !!pt && getComputedStyle(pt).display !== 'none',
               src: pt ? (pt.currentSrc || pt.src) : null };
    }""")
    check("reduced-motion uses poster", bool(poster_visible.get("posterShown")), json.dumps(poster_visible))
    page3.screenshot(path=str(OUT / "arthur_hero_poster.png"))

    # 6. no console errors (filter expected noise)
    real_errs = [e for e in errs if "401" not in e and "404" not in e
                 and "failed to load resource" not in e]
    check("no unexpected console errors", len(real_errs) == 0, " | ".join(real_errs[:3]))

    browser.close()

failed = [n for n, ok, _ in results if not ok]
print("\n=== SUMMARY: %d checks, %d failed ===" % (len(results), len(failed)))
for n, ok, info in results:
    if not ok:
        print("  FAIL:", n, "-", info)
sys.exit(1 if failed else 0)
